export const menuOptions = {
  ceo: [
    { name: 'Home', icon: <img src="home.png" />, route: '/home' },
    { name: 'Branches', icon: <img src="branch.png" />, route: '/branches' },
    { name: 'Asserts', icon: <img src="asserts.png" />, route: '/asserts' },
    { name: 'Staff', icon: <img src="users.png" />, route: '/staff' },
    { name: 'Clients', icon: <img src="clients.png" />, route: '/clients' },
    { name: 'Vendors', icon: <img src="vendors.png" />, route: '/vendors' },
    {
      name: 'Sub Dealers',
      icon: <img src="subdealers.png" />,
      route: '/sub_dealers',
    },
    { name: 'Products', icon: <img src="products.png" />, route: '/products' },
    {
      name: 'Product Assign',
      icon: <img src="product_assign.png" />,
      route: '/products_assign',
    },
    {
      name: 'Request Raise',
      icon: <img src="request_raise.png" />,
      route: '/requests',
    },
    { name: 'Tracker', icon: <img src="tracker.png" />, route: '/tracker' },
    { name: 'Vouchers', icon: <img src="vouchers.png" />, route: '/vouchers' },
    { name: 'Reports', icon: <img src="reports.png" />, route: '/reports' },
    {
      name: 'Work Allocation',
      icon: <img src="work_allocation.png" />,
      route: '/work_allocation',
    },
    { name: 'Invoices', icon: <img src="invoices.png" />, route: '/invoice' },
    { name: 'Estimate', icon: <img src="estimate.png" />, route: '/estimate' },
    { name: 'Day Book', icon: <img src="day_book.png" />, route: '/day-book' },
    { name: 'Analysis', icon: <img src="analysis.png" />, route: '/analysis' },
    { name: 'Ledger', icon: <img src="ledger.png" />, route: '/ledger' },
    { name: 'Payments', icon: <img src="payments.png" />, route: '/payments' },
    { name: 'Receipt', icon: <img src="receipt.png" />, route: '/receipts' },
    { name: 'Hiring', icon: <img src="hiring.png" />, route: '/hiring' },
    { name: 'Tickets', icon: <img src="tickets.png" />, route: '/tickets' },
    {
      name: 'Appointments',
      icon: <img src="appointments.png" />,
      route: '/appointments',
    },
    { name: 'Purchase', icon: <img src="purchase.png" />, route: '/purchase' },
  ],
  subdealer: [
    { name: 'Home', icon: <img src="home.png" />, route: '/home' },
    { name: 'Branches', icon: <img src="branch.png" />, route: '/branches' },
    { name: 'Asserts', icon: <img src="asserts.png" />, route: '/branches' },
    { name: 'Staff', icon: <img src="users.png" />, route: '/staff' },
    { name: 'Clients', icon: <img src="clients.png" />, route: '/branches' },
    { name: 'Vendors', icon: <img src="vendors.png" />, route: '/branches' },
    {
      name: 'Sub Dealers',
      icon: <img src="subdealers.png" />,
      route: '/sub_dealers',
    },
    { name: 'Products', icon: <img src="products.png" />, route: '/products' },
    { name: 'Product Assign', icon: <img src="product_assign.png" /> },
    {
      name: 'Request Raise',
      icon: <img src="request_raise.png" />,
      route: '/requests',
    },
    { name: 'Tracker', icon: <img src="tracker.png" /> },
    { name: 'Vouchers', icon: <img src="vouchers.png" /> },
    { name: 'Reports', icon: <img src="reports.png" />, route: '/reports' },
    {
      name: 'Work Allocation',
      icon: <img src="work_allocation.png" />,
      route: '/work_allocation',
    },
    { name: 'Invoices', icon: <img src="invoices.png" />, route: '/invoice' },
    { name: 'Estimate', icon: <img src="estimate.png" />, route: '/estimate' },
    { name: 'Day Book', icon: <img src="day_book.png" /> },
    { name: 'Analysis', icon: <img src="analysis.png" />, route: '/analysis' },
    { name: 'Ledger', icon: <img src="ledger.png" />, route: '/ledger' },
    { name: 'Payments', icon: <img src="payments.png" />, route: '/payments' },
    { name: 'Receipt', icon: <img src="receipt.png" />, route: '/receipts' },
    { name: 'Hiring', icon: <img src="hiring.png" />, route: '/hiring' },
    { name: 'Tickets', icon: <img src="tickets.png" />, route: '/tickets' },
  ],
};

export const formattedPaths = {
  ceo: {
    '/home': { name: 'Home', icon: <img src="home.png" /> },
    '/branches': { name: 'Branches', icon: <img src="branch.png" /> },
    '/add-branch': { name: 'Add Branch', icon: <img src="branch.png" /> },
    '/edit-branch': { name: 'Edit Branch', icon: <img src="branch.png" /> },
    '/branch-details': {
      name: 'Branch Details',
      icon: <img src="branch.png" />,
    },
    '/staff': { name: 'Staff', icon: <img src="users.png" /> },
    '/add-staff': { name: 'Add Staff', icon: <img src="users.png" /> },
    '/edit-staff': { name: 'Edit Staff', icon: <img src="users.png" /> },
    '/products': { name: 'Products', icon: <img src="products.png" /> },
    '/add-product': { name: 'Add Product', icon: <img src="products.png" /> },
    '/asserts': { name: 'Asserts', icon: <img src="asserts.png" /> },
    '/add-assets': { name: 'Add Asset', icon: <img src="asserts.png" /> },
    '/estimate': { name: 'Estimates', icon: <img src="estimate.png" /> },
    '/add-estimate': { name: 'Add Estimate', icon: <img src="estimate.png" /> },
    '/estimate-details': {
      name: 'Estimate Details',
      icon: <img src="estimate.png" />,
    },
    '/invoice': { name: 'Invoices', icon: <img src="invoice.png" /> },
    '/add-invoice': { name: 'Add Invoice', icon: <img src="invoice.png" /> },
    '/invoice-details': {
      name: 'Invoice Details',
      icon: <img src="invoice.png" />,
    },
    '/payments': { name: 'Payments', icon: <img src="payments.png" /> },
    '/requests': { name: 'Requests', icon: <img src="request.png" /> },
    '/add-request': { name: 'Add Request', icon: <img src="request.png" /> },
    '/delete-request': {
      name: 'Delete Request',
      icon: <img src="delete_request.png" />,
    },
    '/request-details': {
      name: 'Request Details',
      icon: <img src="request_details.png" />,
    },
    '/clients': { name: 'Clients', icon: <img src="clients.png" /> },
    '/add-client': { name: 'Add Client', icon: <img src="clients.png" /> },
    '/delete-client': {
      name: 'Delete Client',
      icon: <img src="delete_client.png" />,
    },
    '/client-details': {
      name: 'Client Details',
      icon: <img src="client_details.png" />,
    },
    '/products_assign': {
      name: 'Product Assign',
      icon: <img src="product_assign.png" />,
    },
    '/add-product-assign': {
      name: 'Add Product Assign',
      icon: <img src="product_assign.png" />,
    },
    '/delete-product-assign': {
      name: 'Delete Product Assign',
      icon: <img src="delete_product_assign.png" />,
    },
    '/vendors': { name: 'Vendors', icon: <img src="vendors.png" /> },
    '/add-vendor': { name: 'Add Vendor', icon: <img src="vendors.png" /> },
    '/delete-vendor': {
      name: 'Delete Vendor',
      icon: <img src="delete_vendor.png" />,
    },
    '/sub_dealers': { name: 'Sub Dealers', icon: <img src="subdealers.png" /> },
    '/add-sub-dealer': {
      name: 'Add Sub Dealer',
      icon: <img src="subdealers.png" />,
    },
    '/delete-sub-dealer': {
      name: 'Delete Sub Dealer',
      icon: <img src="delete_subdealer.png" />,
    },
    '/vouchers': { name: 'Vouchers', icon: <img src="vouchers.png" /> },
    '/work_allocation': {
      name: 'Work Allocation',
      icon: <img src="work_allocation.png" />,
    },
    '/ledger': { name: 'Ledger', icon: <img src="ledger.png" /> },
    '/tickets': { name: 'Tickets', icon: <img src="tickets.png" /> },
    '/hiring': { name: 'Hiring', icon: <img src="hiring.png" /> },
    '/add-hiring': { name: 'Add Hiring', icon: <img src="hiring.png" /> },
    '/delete-hiring': {
      name: 'Delete Hiring',
      icon: <img src="delete_hiring.png" />,
    },
    '/edit-hiring': {
      name: 'Edit Hiring',
      icon: <img src="edit_hiring.png" />,
    },
    '/hiring-details': {
      name: 'Hiring Details',
      icon: <img src="hiring_details.png" />,
    },
    '/receipts': { name: 'Receipts', icon: <img src="receipts.png" /> },
    '/analysis': { name: 'Analysis', icon: <img src="analysis.png" /> },
    '/reports': { name: 'Reports', icon: <img src="reports.png" /> },
    '/download': { name: 'Download', icon: <img src="download.png" /> },
    '/settings': { name: 'Settings', icon: <img src="settings.png" /> },
    '/profile': { name: 'Profile', icon: <img src="profile.png" /> },
    '/day-book': { name: 'Day Book', icon: <img src="day_book.png" /> },
    '/ledger-details': {
      name: 'Ledger Details',
      icon: <img src="ledger_details.png" />,
    },
    '/purchase': { name: 'Purchase', icon: <img src="purchase.png" /> },
    '/payroll': { name: 'Payroll', icon: <img src="payroll.png" /> },
    '/in-hand-product': {
      name: 'In Hand Products',
      icon: <img src="in_hand_products.png" />,
    },
    '/tracker': { name: 'Tracker', icon: <img src="tracker.png" /> },
    '/appointments': {
      name: 'Appointments',
      icon: <img src="appointments.png" />,
    },
    '/add-appointment': {
      name: 'Add Appointment',
      icon: <img src="appointments.png" />,
    },
    '/appointment-details': {
      name: 'Appointment Details',
      icon: <img src="appointments.png" />,
    },
  },
  subdealer: {
    '/home': { name: 'Home', icon: <img src="home.png" /> },
    '/branches': { name: 'Branches', icon: <img src="branch.png" /> },
    '/add-branch': { name: 'Add Branch', icon: <img src="branch.png" /> },
    '/edit-branch': { name: 'Edit Branch', icon: <img src="branch.png" /> },
    '/branch-details': {
      name: 'Branch Details',
      icon: <img src="branch.png" />,
    },
    '/staff': { name: 'Staff', icon: <img src="users.png" /> },
    '/products': { name: 'Products', icon: <img src="products.png" /> },
    '/requests': { name: 'Requests', icon: <img src="request.png" /> },
    '/vouchers': { name: 'Vouchers', icon: <img src="vouchers.png" /> },
    '/work_allocation': {
      name: 'Work Allocation',
      icon: <img src="work_allocation.png" />,
    },
    '/tracker': { name: 'Tracker', icon: <img src="tracker.png" /> },
    '/appointments': {
      name: 'Appointments',
      icon: <img src="appointments.png" />,
    },
    '/download': { name: 'Download', icon: <img src="download.png" /> },
  },
};

export const pageTitles = {
  clients: 'Clients Details',
  product_assign: 'Product Assign',
  vendors: 'Vendor Details',
  sub_dealers: 'Sub Dealers',
  receipts: 'Receipts',
  hiring: 'Hiring',
  invoice: 'Invoices',
  estimate: 'Estimates',
};
